routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PartController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProposalController;
use App\Http\Controllers\RFQController;
use App\Http\Controllers\ContactPersonController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\PriceController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'login_view']);
Route::post('/login',[LoginController::class,'login_web'])->name('login');
Route::get('/forget-password',[LoginController::class,'forget_password']);
Route::post('/send-forget-password-link',[LoginController::class,'send_forget_password_link']);
Route::get('reset-password/{token}', [LoginController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [LoginController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::group(['middleware' => ['CheckAuth','RevalidateBackHistory']], function ()
{
    Route::get('/dashboard', [HomeController::class, 'dashboard_view']);
    Route::get('/contracts', [HomeController::class, 'dashboard_view']);
    Route::get('/logout',[LoginController::class,'logout']);
    Route::post('/update-profile',[HomeController::class,'update_profile']);
    Route::post('/change-password',[HomeController::class,'change_password']);
    Route::group(['prefix' => 'notification'], function ()
    {
        Route::get('/',[HomeController::class,'notification_view']);
        Route::post('/search-notification',[HomeController::class,'search_notification']);
        Route::post('/delete-single-notification',[HomeController::class,'delete_single_notification']);
    });
    Route::group(['prefix' => 'parts'], function ()
    {
        Route::get('/', [PartController::class, 'part_view']);
        Route::get('/add', [PartController::class, 'add_part_view']);
        Route::get('/edit/{part_id}', [PartController::class, 'edit_part_view']);
        Route::post('/add-update-part', [PartController::class, 'add_update_parts']);
        Route::post('/import-parts', [PartController::class, 'import_part_data']);
        Route::post('/export-parts', [PartController::class, 'export_part_data']);
        Route::post('/search-parts', [PartController::class, 'search_parts']);
        Route::post('/delete-single-part', [PartController::class, 'delete_single_part']);
    });
    Route::group(['prefix' => 'inventory'], function ()
    {
        Route::get('/', [InventoryController::class, 'inventory_view']);
        Route::post('/get-parts-list', [PartController::class, 'get_part_list']);
        Route::post('/add-inventory', [InventoryController::class, 'add_part_inventory']);
        Route::post('/search-inventory', [InventoryController::class, 'search_inventory']);
        Route::post('/delete-single-inventory', [InventoryController::class, 'delete_single_inventory']);
    });
    Route::group(['prefix' => 'role-and-permission'], function ()
    {
        Route::get('/', [RoleController::class, 'role_permission_view']);
        Route::post('/search-roles',[RoleController::class,'search_roles']);
        Route::post('/get-role-permission',[RoleController::class,'get_role_permission_view']);
        Route::post('/update-role-permission',[RoleController::class,'update_permission_status']);
        Route::get('/single-role-detail/{role_id}',[RoleController::class,'get_single_role_detail']);
        Route::post('/add-update-roles',[RoleController::class,'add_update_roles']);
        Route::post('/delete-single-role',[RoleController::class,'delete_single_role']);
    });
    Route::group(['prefix' => 'users'], function ()
    {
        Route::get('/', [UserController::class, 'user_view']);
        Route::post('/add-update-user', [UserController::class, 'add_update_user']);
        Route::post('/search-users', [UserController::class, 'search_users']);
        Route::get('/single-user-detail/{user_id}', [UserController::class, 'single_user_detail']);
        Route::post('/delete-single-user', [UserController::class, 'delete_single_user']);
        Route::post('/export-users', [UserController::class, 'user_export_data']);
        Route::post('/update-user-status', [UserController::class, 'update_user_status']);
    });
    Route::group(['prefix' => 'proposal'], function ()
    {
        Route::get('/', [ProposalController::class, 'proposal_view']);
        Route::post('/add-update-proposal', [ProposalController::class, 'add_update_proposal']);
        Route::post('/search-proposal', [ProposalController::class, 'search_proposal']);
        Route::get('/single-proposal-detail/{proposal_id}', [ProposalController::class, 'single_proposal_detail']);
        Route::post('/delete-single-proposal', [ProposalController::class, 'delete_single_proposal']);
        Route::get('/view/{id}', [ProposalController::class, 'single_proposal_view']);
        Route::post('/get-parts-list', [ProposalController::class, 'get_part_list']);
        Route::get('/single-item-detail/{part_id}/{proposal_id}', [ProposalController::class, 'single_item_detail']);
        Route::post('/add-item', [ProposalController::class, 'add_update_proposal_item']);
        Route::post('/search-proposal-item', [ProposalController::class, 'search_proposal_item']);
        Route::get('/single-proposal-item/{id}', [ProposalController::class, 'single_proposal_item']);
        Route::post('/delete-proposal-item', [ProposalController::class, 'delete_proposal_item']);
        Route::post('/update-client-want-status', [ProposalController::class, 'update_client_want_status']);
        Route::get('/new-item-add/{proposal_id}', [PartController::class, 'add_part_view']);
        Route::get('/quotation/{id}', [QuotationController::class, 'client_proposal_quotation']);
        Route::post('/search-client-quotation', [QuotationController::class, 'search_client_quotation']);
        Route::get('/single-rfq-item-with-quotation/{id}', [QuotationController::class, 'single_rfq_item_with_quotation']);
        Route::post('/export-client-quotation', [QuotationController::class, 'export_client_quotation']);
        Route::post('/quotation/update-client-new-price', [QuotationController::class, 'update_client_new_price']);
    });
    Route::group(['prefix' => 'rfq'], function ()
    {
        Route::get('/', [RFQController::class, 'rfq_view']);
        Route::post('/search-rfq', [RFQController::class, 'search_rfq']);
        Route::get('/view/{id}', [RFQController::class, 'single_rfq_view']);
        Route::post('/search-rfq-item', [RFQController::class, 'search_rfq_item']);
        Route::get('/single-rfq-item/{id}', [RFQController::class, 'single_rfq_item']);
        Route::get('/details/{id}', [RFQController::class, 'rfq_details']);
        Route::post('/search-item-details', [RFQController::class, 'search_rfq_item_details']);
        Route::post('/update-client-price', [RFQController::class, 'update_client_price']);
        Route::post('/submit-quotation', [QuotationController::class, 'submit_quotation_to_client']);
        Route::get('/single-rfq-item-with-quotation/{id}', [QuotationController::class, 'single_rfq_item_with_quotation']);
        Route::group(['prefix' => 'quotation'], function ()
        {
            Route::get('/{proposal_item_id}', [QuotationController::class, 'quotation_view']);
            Route::post('/get-contact-person-list', [ContactPersonController::class, 'get_contact_person_list']);
            Route::post('/add-update-quotation', [QuotationController::class, 'add_update_quotation']);
            Route::post('/search-quotation', [QuotationController::class, 'search_quotation']);
            Route::get('/single-quotation/{quotation_id}', [QuotationController::class, 'get_single_quotation']);
            Route::post('/delete-quotation', [QuotationController::class, 'delete_quotation']);
            Route::post('/update-quotation-status', [QuotationController::class, 'update_quotation_status']);
        });

    });
    Route::group(['prefix' => 'contact-person'], function ()
    {
        Route::get('/', [ContactPersonController::class, 'contact_person_view']);
        Route::post('/add-update-person', [ContactPersonController::class, 'add_update_contact_person']);
        Route::post('/search-person', [ContactPersonController::class, 'search_contact_person']);
        Route::get('/single-contact-person/{person_id}', [ContactPersonController::class, 'single_contact_person']);
        Route::post('/delete-single-contact-person', [ContactPersonController::class, 'delete_contact_person']);
    });
    Route::group(['prefix' => 'prices'], function ()
    {
        Route::get('/', [PriceController::class, 'price_view']);
        Route::post('/add-update-price', [PriceController::class, 'add_update_price'])->name('add_update_price');
        Route::post('/search-price', [PriceController::class, 'search_price'])->name('search_price_data');
        Route::get('/single-price/{id}', [PriceController::class, 'single_price'])->name('edit_part_price');
        Route::post('/delete-price', [PriceController::class, 'delete_price'])->name('delete_part_price');
        Route::post('/part-price-history', [PriceController::class, 'part_price_history'])->name('part_price_history');
        Route::post('/import-prices', [PriceController::class, 'import_price_data'])->name('import_prices');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Facades\Log;
use DB;
use File;
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    // GET USER FULL NAME
    public function getFullNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }
    public function getCreatedAtAttribute($value)
    {
        return  dateFormat($value);
    }
    public function getUserRoleNameAttribute()
    {
        if(!empty($this->role_id))
        {
            $roleData = Role::where('id','=',$this->role_id)->value('role_name');
            if(!empty($roleData))
                return $roleData;
        }
        return "";

    }
    // GET USER FULL IMAGE URL
    public function getFullImageUrlAttribute()
    {
        if(empty($this->image))
            return  asset('/').'assets/img/user.png';
        else
        {
            if(File::exists('public/storage/image/'.$this->image))
                return   asset('/storage/image').'/'.$this->image;
            else
                return  asset('/').'assets/img/user.png';
        }


    }
    // UPDATE USER PROFILE DETAILS
    function update_user_profile($request)
    {
        Log::info(11);
        $obj = User::find($request->id);
        $obj->first_name = $request->first_name;
        $obj->last_name = $request->last_name;
        if($request->hasFile('image')) {
            if (!empty($obj->image)) {
                $full_path_dest = 'storage/app/public/image/' . $obj->image;
                @unlink($full_path_dest);
            }
            $obj->image = upload_image($request->image,'profile_image_');
        }
        $obj->save();
        return $obj;
    }
    function add_update_user($request)
    {
        Log::info(52);
        $id = isset($request->id) && !empty($request->id)?$request->id:0;
        $obj = User::firstOrNew(['id' => $id]);
        if($id == 0)
            $obj->created_by = $request->created_by;
        $obj->first_name = $request->first_name;
        $obj->last_name = $request->last_name;
        $obj->email = $request->email;
        $obj->role_id = $request->role_id;
        if(isset($request->password) && !empty($request->password))
            $obj->password = bcrypt($request->password);
        $obj->status = isset($request->status) && !empty($request->status)?$request->status:0;
        if($request->hasFile('image')) {
            if (!empty($obj->image)) {
                $full_path_dest = 'storage/app/public/image/' . $obj->image;
                @unlink($full_path_dest);
            }
            $obj->image = upload_image($request->image,'user_');
        }
        $obj->save();
        return $obj;
    }
    function search_users($request)
    {
        Log::info(54);
        $query = User::query();
        $query->join('roles AS t3','t3.id','=','users.role_id');
        $query->select('users.*','t3.role_name');
        $query->where('users.role_id', '!=',1);
        if(isset($request->role_id) && $request->role_id != 1)
        {
            if(isset($request->created_by) && !empty($request->created_by))
                $query->where('users.created_by', '=',$request->created_by);
        }
        if(isset($request->search_string) && !empty($request->search_string))
        {
            $query->where(function ($q) use ($request) {
                $q->where(DB::raw('CONCAT(users.first_name," ",users.last_name)'), 'like','%'.$request->search_string.'%')
                    ->orWhere('users.email',  'like','%'.$request->search_string.'%')
                    ->orWhere('t3.role_name',  'like','%'.$request->search_string.'%');
            });

        }
        if(isset($request->filter_order_by) && $request->filter_order_by == 'Name-ASC')
            $query->orderBy('users.first_name','ASC');
        elseif(isset($request->filter_order_by) && $request->filter_order_by == 'Name-DESC')
            $query->orderBy('users.first_name','DESC');
        if(isset($request->filter_order_by) && $request->filter_order_by == 'Date-ASC')
            $query->orderBy('users.created_at','ASC');
        elseif(isset($request->filter_order_by) && $request->filter_order_by == 'Date-DESC')
            $query->orderBy('users.created_at','DESC');
        else
            $query->orderBy('users.created_at','DESC');
        $data = $query->paginate(10);
        return $data;
    }
    function get_single_user($id)
    {
        return User::find($id);
    }
    function delete_single_user($id)
    {
        Log::info(57);
        $data = User::find($id);
        if(!empty($data))
        {
            $full_path_dest = 'storage/app/public/image/' . $data->image;
            @unlink($full_path_dest);
            $data->delete();
        }
        return true;
    }
    function export_user_data($request)
    {
        Log::info(60);
        $query = User::query();
        $query->join('roles AS t3','t3.id','=','users.role_id');
        $query->select('users.first_name','users.last_name','email','t3.role_name','users.created_at');
        $query->where('users.role_id', '!=',1);
        if(isset($request->role_id) && $request->role_id != 1)
        {
            if(isset($request->created_by) && !empty($request->created_by))
                $query->where('users.created_by', '=',$request->created_by);
        }
        if(isset($request->search_string) && !empty($request->search_string))
        {
            $query->where(function ($q) use ($request) {
                $q->where(DB::raw('CONCAT(users.first_name," ",users.last_name)'), 'like','%'.$request->search_string.'%')
                    ->orWhere('users.email',  'like','%'.$request->search_string.'%')
                    ->orWhere('t3.role_name',  'like','%'.$request->search_string.'%');
            });

        }
        if(isset($request->filter_order_by) && $request->filter_order_by == 'Name-ASC')
            $query->orderBy('users.first_name','ASC');
        elseif(isset($request->filter_order_by) && $request->filter_order_by == 'Name-DESC')
            $query->orderBy('users.first_name','DESC');
        if(isset($request->filter_order_by) && $request->filter_order_by == 'Date-ASC')
            $query->orderBy('users.created_at','ASC');
        elseif(isset($request->filter_order_by) && $request->filter_order_by == 'Date-DESC')
            $query->orderBy('users.created_at','DESC');
        else
            $query->orderBy('users.created_at','DESC');
        $data = $query->get();
        return $data;
    }
    // UPDATE USER STATUS
    function update_user_status($request)
    {
        Log::info(61);
        $obj = User::find($request->user_id);
        $obj->status = $request->status;
        $obj->save();
        return $obj;
    }
    function get_admin_data()
    {
        Log::info(89);
        return User::where('role_id','=',1)->first();
    }
}

resources/views/layouts/flash_msg.blade.php
@if(Session::has('success'))
    <p class="alert alert-success common-alert">
        {{ Session::get('success') }}
    </p>
@endif
@if(Session::has('error'))
    <p class="alert alert-danger common-alert">
        {{ Session::get('error') }}
    </p>
@endif

resources/views/layouts/front_master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@yield('page_title')</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ asset('/') }}assets/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="{{ asset('/') }}assets/css/bootstrap.css.map">
    <link rel="stylesheet" href="{{ asset('/') }}assets/css/bootstrap.min.css">

    <!-- Your custom styles -->
    <link rel="stylesheet" href="{{ asset('/') }}assets/css/custom.css">
    <link rel="stylesheet" href="{{ asset('/') }}assets/css/login.css">
    <link rel="stylesheet" href="{{ asset('/') }}assets/css/form.css">
        <link rel="stylesheet" href="{{ asset('/my_assets') }}/fonts/stylesheet.css">
    @yield('style')
    <style>
        .form-control:disabled, .form-control[readonly] {
            background-color: unset;
        }
        .loader {
            margin-top: 10%;
            margin-left: 50%;
            border: 16px solid #f3f3f3;
            border-radius: 50%;
            border-top: 16px solid #037ecc;
            border-bottom: 16px solid #037ecc;
            border-right: 16px solid #1381d5;
            border-left: 16px solid #1381d5;
            width: 100px;
            height: 100px;
            -webkit-animation: spin 2s linear infinite;
            animation: spin 2s linear infinite;
        }

        @-webkit-keyframes spin {
            0% { -webkit-transform: rotate(0deg); }
            100% { -webkit-transform: rotate(360deg); }
        }

        @keyframes    spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }

        .loader-box
        {
            display: block;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            position: fixed;
            opacity: 1;
            background-color: #fff;
            z-index: 999999999999;
            text-align: center;

        }
        .loader-box .flex-center{
            height: 100%;
            align-items: center;
            justify-content: center;
            display: flex;
            width: 100%;
            padding: 10px;
        }

    </style>
</head>
<body>
<div class="loader-box"  id="loader">
    <div class="flex-center">
        <img style="height: 50%;width: auto;" src="{{ asset('/default_icon/loader-logo3.gif') }}"/>
    </div>
</div>
    @yield('section')

    <script type="text/javascript" src="{{ asset('/') }}assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('/') }}assets/js/popper.min.js"></script>
    <script type="text/javascript" src="{{ asset('/') }}assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ asset('/my_assets') }}/jquery.validate.min.js"></script>
    @yield('script')
    <script type="text/javascript">
        $(document).ready(function () {
            $('.common-alert').delay(3000).fadeOut();
        });
        $(document).ready(function() {
            $('#loader').fadeOut('slow');
        });
    </script>
</body>
</html>

resources/views/layouts/header.blade.php
@php $segment1 = Request::segment(1) @endphp
<header class="home-header main_header">
    <div class="container-fluid">
        <div class="sty_header_inner">
            <div class="row">
                <div class="col-md-7 dp_col">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        @if(isset($module_data) && count($module_data) != 0)
                            @foreach($module_data AS $key => $value)
                                @php $url_explode = explode('/',$value->url); @endphp
                                @if(isset($url_explode[1]) && $segment1 == $url_explode[1])
                                    <li class="nav-item" onclick="window.location.href='{{ url($value->url) }}'" style="cursor: pointer;">
                                       <div class="d-flex align-items-center">
                                           <a href="javascript:void(0)" class="back_btn"><i class="fas fa-chevron-left"></i></a>
                                           <img src="{{ url($value->icon) }}"  alt="">
                                           <span> {{ $value->module_name }}</span>
                                       </div>
                                    </li>
                                @endif
                            @endforeach
                        @endif
                    </ul>
                </div>
                <div class="col-md-5">
                    <nav class="navbar navbar-expand-sm navbar-dark">
                        <button type="button" class="btn toggle_btn sidebarclose_btn">
                            <div class="lineOne"></div>
                            <div class="lineTwo"></div>
                            <div class="lineThree"></div>
                        </button>
                        <!-- Links -->
                        <ul class="navbar-nav justify-content-end">
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <img class="setting_img" src="{{ asset('/') }}assets/img/setting_icon.svg" alt="">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('/logout') }}">
                                    <img class="logout_img" src="{{ asset('/') }}assets/img/logout_icon.svg" alt="">
                                </a>
                            </li>
                            <!-- Dropdown -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="navbardrop" data-toggle="dropdown">
                                    @if(isset($auth_user->full_image_url))
                                        <img src="{{ $auth_user->full_image_url }}" id="user_full_image_url_preview" class="pro-img" alt="">
                                    @endif
                                    <span id="user_full_name_text">@if(isset($auth_user->full_name)){{ $auth_user->full_name }}@endif</span>
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="javascript:void(0)" type="button" data-toggle="modal" data-target="#EditProfileModal">Edit Profile</a>
                                    <a class="dropdown-item" href="javascript:void(0)" onclick="show_change_password_modal()">Change Password</a>
                                    <a class="dropdown-item" href="{{ url('/notification') }}">Notification</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-7 mb_col">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <img src="{{ asset('/') }}assets/img/proposal.png" alt="">
                            <span>Proposal</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    <div>


</header>{{--
<header class="home-header main_header no-border-bottom">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-sm navbar-dark">
                    <button type="button" class="btn toggle_btn sidebarclose_btn">
                        <div class="lineOne"></div>
                        <div class="lineTwo"></div>
                        <div class="lineThree"></div>
                    </button>

                    <!-- Links -->
                    <ul class="navbar-nav justify-content-end">
                        <li class="nav-item search_box">
                            <form method="get" action="#" class="header_search">
                                <div class="form-group">
                                    <input type="text" class="form-control" autocomplete="off" name="" placeholder="" required="">
                                    <img class="search_img" src="{{ asset('/') }}assets/img/search-icon.png" alt="">
                                    <button type="submit" class="btn btn-sm search_btn"><img src="{{ asset('/') }}assets/img/right-arrow.png" alt=""></button>
                                </div>
                            </form>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <img class="setting_img" src="{{ asset('/') }}assets/img/setting_icon.svg" alt="">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url('/logout') }}">
                                <img class="logout_img" src="{{ asset('/') }}assets/img/logout_icon.svg" alt="">
                            </a>
                        </li>
                        <!-- Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="navbardrop" data-toggle="dropdown">
                                @if(isset($auth_user->full_image_url))
                                    <img src="{{ $auth_user->full_image_url }}" id="user_full_image_url_preview" class="pro-img" alt="">
                                @endif
                                <span id="user_full_name_text">@if(isset($auth_user->full_name)){{ $auth_user->full_name }}@endif</span>
                             --}}{{--   <img src="{{ asset('/') }}assets/img/profile-img.jpg" class="pro-img" alt="">
                                    John Doe--}}{{--
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="javascript:void(0)" type="button" data-toggle="modal" data-target="#EditProfileModal">Edit Profile</a>
                                <a class="dropdown-item" href="javascript:void(0)" onclick="show_change_password_modal()">Change Password</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>--}}

resources/views/layouts/sidebar.blade.php
@php $segment1 = Request::segment(1) @endphp
<aside class="admin-sidebar">
    <form class=" serch_bar">
        <input  type="search" id="search_sidebar_input" onkeyup="search_sidebar()" placeholder="Search" aria-label="Search">
        <button class="serch_btn" type="submit">
            <img src="{{ asset('/') }}assets/img/search-icon.png" alt="">
        </button>
    </form>
    <a href="#" class="closebtn mob_closebtn">×</a>

    <div class="admin-sidebar-brand">
        <button type="button" class="btn toggle_btn sidebar_add_btn">
      <!--       <div class="lineOne"></div>
            <div class="lineTwo"></div>
            <div class="lineThree"></div> -->
            <img src="{{ asset('/') }}assets/img/toglebar_icon.svg" alt="">
        </button>
    </div>
    <div class="sidebar-main-wrapper">
        <div class="admin-sidebar-wrapper">
            <ul class="menu" id="sidebar_search_box">
                <li class="menu-item @if($segment1 == 'dashboard') active @endif">
                    <a href="{{ url('/dashboard') }}" class="menu-link">
                        <span class="menu-label">
                            <img src="{{ asset('/') }}assets/img/dashboard_icon.svg" alt="">
                        </span>
                        <span class="menu-icon">
                            Dashboard
                        </span>
                    </a>
                </li>
                @if(isset($module_data) && count($module_data) != 0)
                    @foreach($module_data AS $key => $value)
                        @php $url_explode = explode('/',$value->url); @endphp
                        @php $active_class = 0; @endphp
                        @if(isset($url_explode[1]) && $segment1 == $url_explode[1])
                            @php $active_class = 1; @endphp
                        @endif


                        <li class="menu-item  @if($active_class == 1)  active @endif" @if($active_class == 1)  id="sidebarActiveId" @endif>
                            <a href="{{ url($value->url) }}" class="menu-link">
                                <span class="menu-label">
                                    <img src="{{ url($value->icon) }}" alt="">
                                </span>
                                <span class="menu-icon">{{ $value->module_name }}</span>
                            </a>
                        </li>
                    @endforeach
                @endif
            </ul>
        </div>
    </div>
</aside>